#!/usr/bin/env python3
"""
Hermes Radio — Broadcast Engine
===============================
Dual-mode (audio/text) with hybrid data sourcing.

Segments are defined in config.yaml with per-segment source:
  - searxng:  fetched from your SearXNG instance (zero-token)
  - bank:     rotated from a content bank text file (zero-token)
  - llm:      generated by the Hermes agent (uses tokens)
  - literal:  inline text from template (no data needed)

Workflow modes:
  python3 broadcast.py                           # full pipeline (legacy)
  python3 broadcast.py --step collect            # zero-token data → JSON
  python3 broadcast.py --step build <ctx.json>   # completed context → output
"""

import argparse
import json
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape


# ═══════════════════════════════════════════════════════════════
# CONSTANTS
# ═══════════════════════════════════════════════════════════════

SEGMENT_SOURCES = ("searxng", "bank", "llm", "literal")
VALID_MODES = ("audio", "text")


# ═══════════════════════════════════════════════════════════════
# CONFIG LOADING
# ═══════════════════════════════════════════════════════════════

def load_config(path: Path) -> dict:
    """Load YAML config. Accepts both old flat keys and new segments array."""
    if not path.exists():
        print(f"[error] Config not found: {path}", file=sys.stderr)
        print(f"[info]  Copy config.example.yaml to config.yaml and customize it.", file=sys.stderr)
        sys.exit(1)
    with open(path) as f:
        cfg = yaml.safe_load(f)

    cfg["_config_dir"] = path.resolve().parent
    cfg.setdefault("mode", "audio")
    cfg.setdefault("templates_dir", "templates")
    cfg.setdefault("output", {}).setdefault("directory", "output")
    cfg.setdefault("output", {}).setdefault("cleanup_days", 7)
    cfg.setdefault("searxng", {}).setdefault("timeout", 15)
    cfg.setdefault("tts", {}).setdefault("voice", "en-US-ChristopherNeural")

    # Migrate old flat config to segments if segments not defined
    if "segments" not in cfg:
        cfg["segments"] = _migrate_flat_config(cfg)

    return cfg


def _migrate_flat_config(cfg: dict) -> list[dict]:
    """Convert old headline/music/banks config to segments format."""
    segments = [
        {"id": "intro", "source": "literal", "enabled": True},
    ]
    if cfg.get("headlines", {}).get("enabled", True):
        segments.append({
            "id": "headlines",
            "source": "searxng",
            "enabled": True,
            "params": {
                "query": cfg.get("headlines", {}).get("query",
                            "AI artificial intelligence {month} {year}"),
                "max_results": cfg.get("headlines", {}).get("max_results", 4),
                "category": "news",
            },
        })
    for key, bank_path in cfg.get("content", {}).get("banks", {}).items():
        segments.append({
            "id": key,
            "source": "bank",
            "enabled": True,
            "params": {"bank_path": bank_path},
        })
    if cfg.get("music", {}).get("enabled", True):
        segments.append({
            "id": "music",
            "source": "searxng",
            "enabled": True,
            "params": {
                "max_results": cfg.get("music", {}).get("max_results", 1),
                "category": "videos",
            },
        })
    segments.append({"id": "outro", "source": "literal", "enabled": True})
    return segments


# ═══════════════════════════════════════════════════════════════
# CONTENT BANKS
# ═══════════════════════════════════════════════════════════════

def load_bank(path: Path) -> list[str]:
    """Load content bank: one item per line, blank/comment lines ignored."""
    if not path.exists():
        return []
    items = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                items.append(line)
    return items


def pick_today(bank: list[str]) -> str:
    """Deterministic day-of-year rotation."""
    if not bank:
        return ""
    doy = datetime.now().timetuple().tm_yday
    return bank[doy % len(bank)]


# ═══════════════════════════════════════════════════════════════
# SEARXNG
# ═══════════════════════════════════════════════════════════════

def searxng_fetch(base_url: str, query: str, category: str = "news",
                  max_results: int = 5, timeout: int = 15) -> list[str]:
    """Query SearXNG and return deduplicated result titles."""
    url = (f"{base_url.rstrip('/')}/search"
           f"?q={urllib.parse.quote(query)}"
           f"&format=json&categories={category}&pageno=1")
    try:
        req = urllib.request.Request(url, headers={
            "User-Agent": "HermesRadio/1.0",
            "Accept": "application/json",
        })
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode())

        seen = set()
        results = []
        for r in data.get("results", []):
            title = r.get("title", "").strip()
            if not title:
                continue
            key = "".join(c.lower() for c in title[:60] if c.isalnum())
            if key and key not in seen:
                seen.add(key)
                results.append(title)
                if len(results) >= max_results:
                    break
        return results
    except Exception as e:
        print(f"[warn] SearXNG ({category}) failed: {e}", file=sys.stderr)
        return []


# ═══════════════════════════════════════════════════════════════
# SEGMENT COLLECTORS
# ═══════════════════════════════════════════════════════════════

def collect_segment(seg: dict, ctx: dict, config_dir: Path,
                    searxng_base: str, searxng_timeout: int):
    """Run a single segment's data collection. Returns (value, llm_prompt_info)."""
    sid = seg["id"]
    source = seg.get("source", "literal")
    params = seg.get("params", {})

    if source == "searxng":
        query_tpl = params.get("query", f"{{month}} {{year}}")
        query = query_tpl.format(**ctx)
        results = searxng_fetch(
            searxng_base, query,
            params.get("category", "news"),
            params.get("max_results", 5),
            searxng_timeout,
        )
        category = params.get("category", "news")
        if category == "videos":
            return results[0] if results else "", None
        return results, None

    if source == "bank":
        bank_path = config_dir / params.get("bank_path", "")
        bank = load_bank(bank_path)
        return pick_today(bank), None

    if source == "llm":
        prompt = seg.get("prompt", "") or params.get("prompt", "")
        model_hint = seg.get("model_hint", "") or params.get("model_hint", "")
        # Enrich ctx with string versions of lists and counts
        enrich = {}
        for k, v in ctx.items():
            if isinstance(v, list):
                enrich[f"{k}_str"] = "\n".join(str(x) for x in v)
                enrich[f"n_{k}"] = len(v)
        try:
            filled_prompt = prompt.format(**ctx, **enrich)
        except KeyError as e:
            filled_prompt = prompt
        return "", {
            "id": sid,
            "prompt": filled_prompt,
            "model_hint": model_hint,
            "output": None,
        }

    # literal source — no data needed
    return None, None


# ═══════════════════════════════════════════════════════════════
# JSON OUTPUT
# ═══════════════════════════════════════════════════════════════

def build_build_json(
    segments: list[dict],
    config_dir: Path,
    searxng_base: str,
    searxng_timeout: int,
    output_format: str,
) -> dict:
    """Collect all non-LLM segment data and produce a build context JSON."""
    today = datetime.now()
    ctx = {
        "date": today.strftime("%A, %B %d, %Y"),
        "short_date": today.strftime("%Y%m%d"),
        "year": today.year,
        "month": today.strftime("%B"),
    }

    build = {
        "meta": {
            "generated_at": today.isoformat(),
            "output_format": output_format,
        },
        "ctx": {**ctx},
        "llm_needed": [],
    }

    for seg in segments:
        if not seg.get("enabled", True):
            continue
        val, llm_info = collect_segment(
            seg, ctx, config_dir, searxng_base, searxng_timeout,
        )
        if llm_info:
            build["llm_needed"].append(llm_info)
            ctx[seg["id"]] = ""
        elif val is not None:
            ctx[seg["id"]] = val

    build["ctx"] = ctx

    return build


# ═══════════════════════════════════════════════════════════════
# TTS
# ═══════════════════════════════════════════════════════════════

def generate_tts(text: str, voice: str, output_path: Path) -> Path:
    cmd = ["uv", "run", "edge-tts", "--voice", voice,
           "--text", text, "--write-media", str(output_path)]
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    if result.returncode != 0:
        raise RuntimeError(f"TTS failed (exit {result.returncode}): {result.stderr}")
    if not output_path.exists() or output_path.stat().st_size == 0:
        raise RuntimeError("TTS produced empty output file")
    return output_path


def get_audio_duration(path: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries",
         "format=duration", "-of",
         "default=noprint_wrappers=1:nokey=1", str(path)],
        capture_output=True, text=True, timeout=30,
    )
    try:
        return float(result.stdout.strip())
    except (ValueError, TypeError):
        return 0.0


def cleanup_old(directory: Path, keep_days: int):
    cutoff = datetime.now().timestamp() - keep_days * 86400
    for f in directory.glob("hermes-radio-*.mp3"):
        if f.stat().st_mtime < cutoff:
            f.unlink(missing_ok=True)


# ═══════════════════════════════════════════════════════════════
# TEMPLATE RENDERING
# ═══════════════════════════════════════════════════════════════

def render_template(template_path: Path, context: dict) -> str:
    env = Environment(
        loader=FileSystemLoader(str(template_path.parent)),
        autoescape=select_autoescape(default=False),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    template = env.get_template(template_path.name)
    return template.render(**context)


# ═══════════════════════════════════════════════════════════════
# BUILD — final assembly from a completed context
# ═══════════════════════════════════════════════════════════════

def run_build(build_json: dict, cfg: dict, templates_dir: Path, output_dir: Path):
    """Render templates and (for audio mode) generate TTS/FFmpeg output.

    The build_json must have all llm_needed outputs filled in (by the agent).
    """
    ctx = build_json["ctx"]
    output_format = build_json.get("meta", {}).get("output_format", cfg.get("mode", "audio"))

    if output_format == "audio":
        # ── Render TTS script ──
        tts_text = render_template(templates_dir / "tts_script.txt.j2", ctx)
        if not tts_text.strip():
            print("[error] TTS template rendered empty — check templates/tts_script.txt.j2", file=sys.stderr)
            sys.exit(1)

        # ── Generate speech ──
        voice = cfg.get("tts", {}).get("voice", "en-US-ChristopherNeural")
        output_file = output_dir / f"hermes-radio-{ctx['short_date']}.mp3"
        print(f"  Generating TTS ({voice})...", file=sys.stderr)
        generate_tts(tts_text, voice, output_file)

        # ── Duration ──
        duration = get_audio_duration(output_file)
        ctx["duration"] = f"{duration:.0f}"

        # ── Cleanup ──
        cleanup_old(output_dir, cfg["output"]["cleanup_days"])

        # ── Render caption ──
        caption = render_template(templates_dir / "telegram.md.j2", {**ctx, "mode": "audio"})
        print(caption)
        print(f"MEDIA:{output_file}")

    else:
        caption = render_template(templates_dir / "telegram.md.j2", {**ctx, "mode": "text"})
        print(caption)


# ═══════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="Hermes Radio — Broadcast Engine",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python3 broadcast.py                           # full pipeline (audio)\n"
            "  python3 broadcast.py --mode text                # full pipeline (text)\n"
            "  python3 broadcast.py --step collect             # zero-token data → JSON\n"
            "  python3 broadcast.py --step build ctx.json      # build from context\n"
            "  python3 broadcast.py --render template.j2 ctx.json  # render any template\n"
        ),
    )
    parser.add_argument("-c", "--config", default="config.yaml",
                        help="Path to config.yaml")
    parser.add_argument("-m", "--mode", choices=list(VALID_MODES), default=None,
                        help="Override output format (audio/text)")
    parser.add_argument("--step", choices=["collect", "build"], default=None,
                        help="Pipeline step: collect (data → JSON) or build (context → output)")
    parser.add_argument("--render", metavar="TEMPLATE",
                        help="Render a specific template file with context JSON and print to stdout")
    parser.add_argument("context_file", nargs="?",
                        help="Path to context JSON (required for --step build)")
    args = parser.parse_args()

    # Load config
    cfg_path = Path(args.config).resolve()
    cfg = load_config(cfg_path)

    if args.mode:
        cfg["mode"] = args.mode

    config_dir = cfg["_config_dir"]
    templates_dir = config_dir / cfg["templates_dir"]
    output_dir = config_dir / cfg["output"]["directory"]
    output_dir.mkdir(parents=True, exist_ok=True)

    searxng_base = cfg.get("searxng", {}).get("base_url", "")
    searxng_timeout = cfg.get("searxng", {}).get("timeout", 15)

    # ── Step: collect ──
    if args.step == "collect":
        build_json = build_build_json(
            cfg["segments"], config_dir,
            searxng_base, searxng_timeout,
            cfg["mode"],
        )
        print(json.dumps(build_json, indent=2, ensure_ascii=False))
        return

    # ── Step: build ──
    if args.step == "build":
        if not args.context_file:
            print("[error] --step build requires a context JSON file path", file=sys.stderr)
            sys.exit(1)
        ctx_path = Path(args.context_file).resolve()
        if not ctx_path.exists():
            print(f"[error] Context file not found: {ctx_path}", file=sys.stderr)
            sys.exit(1)
        with open(ctx_path) as f:
            build_json = json.load(f)
        run_build(build_json, cfg, templates_dir, output_dir)
        return

    # ── Render arbitrary template ──
    if args.render:
        if not args.context_file:
            print("[error] --render requires a context JSON file path", file=sys.stderr)
            sys.exit(1)
        ctx_path = Path(args.context_file).resolve()
        if not ctx_path.exists():
            print(f"[error] Context file not found: {ctx_path}", file=sys.stderr)
            sys.exit(1)
        with open(ctx_path) as f:
            build_json = json.load(f)
        rendered = render_template(templates_dir / args.render, build_json["ctx"])
        print(rendered)
        return

    # ── No step = full pipeline (legacy) ──
    print(f"Hermes Radio — {datetime.now().strftime('%A, %B %d, %Y')}", file=sys.stderr)
    print(f"Mode: {cfg['mode']}", file=sys.stderr)
    build_json = build_build_json(
        cfg["segments"], config_dir,
        searxng_base, searxng_timeout,
        cfg["mode"],
    )
    n_llm = len(build_json["llm_needed"])
    if n_llm:
        print(f"[info] {n_llm} LLM segments will be empty in full-pipeline mode.", file=sys.stderr)
        print(f"[info] Use --step collect + agent processing + --step build for hybrid.", file=sys.stderr)
    run_build(build_json, cfg, templates_dir, output_dir)


if __name__ == "__main__":
    main()
